#!/usr/bin/env bash
## Run blt setup commands to prepare your local site for
## development.
##
## Usage: fin init
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
# Initialize stack
echo 'Initializing the docksal environment...'
fin project start

unameOut="$(uname -s)"
case "${unameOut}" in
    Linux*)     machine=Linux;;
    Darwin*)    machine=Mac;;
    CYGWIN*)    machine=Cygwin;;
    MINGW*)     machine=MinGw;;
    *)          machine="UNKNOWN:${unameOut}"
esac

# Import the certs
# Should this be a different conditional?
if [[ machine == "MinGw" ]]; then
  echo 'If this is a Windows machine, install the WebNY certs'
	# Run this command manually for windows instead
  fin webny/certs
fi

# Install project requirements
networksetup -setv6off Wi-Fi
echo 'Running Composer commands...'
fin exec COMPOSER_MEMORY_LIMIT=-1
fin exec COMPOSER_ALLOW_XDEBUG=1
fin exec COMPOSER_DISABLE_XDEBUG_WARN=1
fin exec composer clear-cache
# fin exec COMPOSER_PROCESS_TIMEOUT=2000
fin exec composer install
networksetup -setv6automatic Wi-Fi

# Set up blt
cd $DOCROOT_PATH

echo 'Removing non-blt settings files if they exist...'
rm -f $DOCROOT_PATH/sites/default/settings/local.settings.php
rm -f $DOCROOT_PATH/sites/default/local.drush.yml

echo 'Creating local blt.yml file for database settings...'
cp $PROJECT_ROOT/.docksal/default.docksal.local.blt.yml $PROJECT_ROOT/blt/local.blt.yml

echo 'Running blt commands...'
fin blt blt:init:settings
fin blt drupal:install --no-interaction

echo 'Creating local drush file...'
cp $DOCROOT_PATH/sites/default/local.drush.yml $PROJECT_ROOT/local.drush.yml
